baseURL: "lavksingh.github.io" 
title: Lav Kumar Singh
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org
          weight: 6

params:
    description: "This website hosts Lav Kumar Singh's research papers, course materials, curriculum vitae, and contact information."
    author: Lav Kumar Singh
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "May 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr. Lav Kumar Singh
          subtitle: "I am a postdoctoral researcher at the Institute of Mathematics, Physics and Mechanics (IMFM), Ljubljana, Slovenia. My primary field of research is Banach algebras and Operator algebras. I am interested in exploring Topological Center problem for the bidual of various Banach algebras originating from a locally compact group. I am also interested in studying various notion of amenability for Banach algebras. Research in these topics require tools from operator algebras, abstract harmonic analysis, geometry of Banach spaces etc."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Papers
              url: papers/
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Courses
              url: courses/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            
    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:lav.singh@imfm.si
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://www.researchgate.net/profile/Lav-Kumar-Singh?ev=hdr_xprf
        - name: GitHub
          url: https://github.com/Lavksingh
        - name: YouTube
          url: https://www.youtube.com/@pmichaillat
       
    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
